version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: transaction_apps
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASS: secret
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: transaction_apps
    # Add the wait-for-it.sh script to ensure the app waits for the db service to be ready
    command: ["./wait-for-it.sh", "db:5432", "--", "./main", "-host=db", "-port=8080"]
